import os
import time
from pathlib import Path
from dotenv import load_dotenv
from google import genai
from google.genai import types

# --- 1. SETUP ---
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    print("❌ API Key missing. Check .env file.")
    exit()

client = genai.Client(api_key=api_key)

# Using your best available models
MODEL_LIST = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-pro"]

# --- 2. THE SUNO OPTIMIZER PROMPT ---
# This instructs Gemini to act like a Suno prompt engineer
system_instruction = (
    "You are an expert Suno AI Song Architect. Your goal is to generate lyrics and style prompts "
    "that result in high-quality, glitch-free audio generation on Suno v3.5/v4.\n\n"
    "RULES FOR OUTPUT:\n"
    "1. **Language & Script:** Write lyrics in Romanized Script (English letters) mixed with the native script "
    "if requested, but prioritize Romanized (Hinglish/Banglish) for correct pronunciation of slang.\n"
    "2. **Structure:** Use Suno Meta Tags strictly: [Intro], [Verse], [Chorus], [Bridge], [Hook], [Outro].\n"
    "3. **Direction:** Add musical cues in brackets like [Heavy Bass Drop], [Sitar Solo], [Aggressive Flow], [Melodic Pause].\n"
    "4. **Style Prompt:** Generate a specialized 'Style Description' string optimized for Suno (max 120 chars).\n"
    "5. **Content:** Capture the vibe of legends (Sidhu Moosewala for aggression, Arijit/Talwinder for soul, etc.)."
)

def get_user_inputs():
    print("\n🎹 --- SUNO AI SONG ARCHITECT --- 🎹")
    topic = input("📝 What is the song about? (e.g. Village boy success): ")
    
    print("\n🌍 Select Language:")
    print("   1. Hindi\n   2. Punjabi\n   3. Haryanvi\n   4. Bengali")
    lang_choice = input("   👉 Choice (1-4 or type name): ")
    
    print("\n🎵 Select Genre:")
    print("   1. HipHop/Rap (Moosewala Style)\n   2. Soulful/Sad (Talwinder Style)\n   3. Sufi/Folk\n   4. Trap/Drill\n   5. Pop/Commercial")
    genre_choice = input("   👉 Choice (1-5 or type name): ")
    
    return topic, lang_choice, genre_choice

def generate_suno_track(topic, language, genre):
    # Construct a rich prompt for Gemini
    full_prompt = (
        f"Create a song for Suno AI.\n"
        f"TOPIC: {topic}\n"
        f"LANGUAGE: {language} (Use Romanized/English script for easy reading + Slang).\n"
        f"GENRE: {genre}.\n\n"
        "OUTPUT FORMAT REQUIRED:\n"
        "SECTION 1: STYLE PROMPT (Keywords for Suno's 'Style of Music' box)\n"
        "SECTION 2: LYRICS (With [Verse], [Chorus] tags and ad-libs like (Burrah, Skrrt))"
    )

    print(f"\n🎧 Architecting track with {language} {genre} vibes...")

    for model_name in MODEL_LIST:
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    temperature=0.9, # Balanced creativity
                )
            )
            return response.text, model_name

        except Exception as e:
            if "429" in str(e):
                time.sleep(1)
            elif "404" in str(e):
                continue # Try next model
            else:
                print(f"⚠️ Error: {e}")
                
    return None, None

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    topic, language, genre = get_user_inputs()
    
    result, model = generate_suno_track(topic, language, genre)
    
    if result:
        print("\n" + "✅"*20)
        print(f"🤖 Generated by: {model}")
        print("✅"*20 + "\n")
        
        # We save it to a file immediately so you don't lose it
        filename = f"SUNO_{topic.replace(' ', '_')}.txt"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(result)
            
        print(result)
        print(f"\n\n💾 SAVED! Open '{filename}' to copy-paste.")
        print("👉 TIP: Paste 'SECTION 1' into Suno's Style Box.")
        print("👉 TIP: Paste 'SECTION 2' into Suno's Lyrics Box.")
    else:
        print("❌ Failed to generate. Check Internet/Quota.")